export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Freenote",
  url: "freenote.app",
  keywords: [
    "AI journal app",
    "AI diary app",
    "journal prompts",
    "how to journal",
    "journaling ideas",
    "gratitude journal prompts",
    "journal writing prompts",
    "journal prompts for mental health",
    "how to start journaling",
    "daily journal prompts",
    "journal prompts for self love",
    "best journal app",
    "benefits of journaling",
    "how to journal for mental health",
    "what to write in a journal",
    "how to journal daily",
    "diary app",
    "AI-assisted note search",
    "AI-assisted note summarization",
    "AI-driven journaling",
    "digital diary with AI",
    "private journaling app",
    "mood tracker",
    "mood tracker app",
    "self care",
    "mental health apps",
    "mindfulness",
    "note-taking application",
    "personal knowledge base",
    "secure note-taking",
  ],
  title: "Freenote - Write Freely, Note Casually",
  description:
    "Freenote is an open-source AI journal app with Markdown support. You can freely record your notes, and with AI assistance, easily search and summarize past entries, enhancing creativity capture and management. All data is stored locally on your device, ensuring privacy and security.",
  twitter: "https://twitter.com/chaoying972",
  domain: "https://freenote.app",
};
