import {
  ArrowUp,
  BookOpenText,
  BotMessageSquare,
  Bug,
  ChevronRight,
  CircleArrowUp,
  CircleHelp,
  CirclePlus,
  Github,
  Loader,
  LucideIcon,
  MessageSquare,
  NotebookPen,
  NotebookText,
  RefreshCw,
  Settings,
  Sparkles,
  StopCircle,
} from "lucide-react";

export const Icons = {
  sparkles: Sparkles,
  notebookText: NotebookText,
  botMessageSquare: BotMessageSquare,
  notebookPen: NotebookPen,
  bookOpenText: BookOpenText,
  arrowUp: ArrowUp,
  loader: Loader,
  chevronRight: ChevronRight,
  circleArrowUp: CircleArrowUp,
  stopCircle: StopCircle,
  settings: Settings,
  refreshCw: RefreshCw,
  circlePlus: CirclePlus,
  github: Github,
  bug: Bug,
  messageSquare: MessageSquare,
  circleHelp: CircleHelp,
} satisfies Record<string, LucideIcon>;
