import {
  ArrowUp,
  BookOpenText,
  BotMessageSquare,
  ChevronRight,
  CircleArrowUp,
  Loader,
  LucideIcon,
  NotebookPen,
  NotebookText,
  RefreshCw,
  Settings,
  Sparkles,
  StopCircle,
} from "lucide-react";

export const Icons = {
  sparkles: Sparkles,
  notebookText: NotebookText,
  botMessageSquare: BotMessageSquare,
  notebookPen: NotebookPen,
  bookOpenText: BookOpenText,
  arrowUp: ArrowUp,
  loader: Loader,
  chevronRight: ChevronRight,
  circleArrowUp: CircleArrowUp,
  stopCircle: StopCircle,
  settings: Settings,
  refreshCw: RefreshCw,
} satisfies Record<string, LucideIcon>;
